# Generated by Django 5.2.8 on 2025-11-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Abarrotes', '0004_remove_venta_productos_vendidos_detalleventa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
